import { jwtVerify, createRemoteJWKSet } from 'jose';
const EVENT='trina-60-2029';
const JSON_HEADERS={'content-type':'application/json;charset=UTF-8','cache-control':'no-store'};
const j=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:JSON_HEADERS});
const clean=v=>typeof v==='string'?v.trim():v;
let jwks;
function getJWKS(env){if(!jwks)jwks=createRemoteJWKSet(new URL(`${env.TEAM_DOMAIN}/cdn-cgi/access/certs`));return jwks;}
async function accessIdentity(request,env,aud){const token=request.headers.get('cf-access-jwt-assertion');if(!token)throw new Error('Missing Cloudflare Access token');const {payload}=await jwtVerify(token,getJWKS(env),{issuer:env.TEAM_DOMAIN,audience:aud});if(!payload.email)throw new Error('Authenticated email missing');return {email:String(payload.email).toLowerCase(),name:String(payload.name||payload.email),sub:String(payload.sub||'')};}
async function eventId(env){const e=await env.DB.prepare('SELECT id FROM events WHERE slug=?').bind(EVENT).first();return e?.id;}
async function upsertUser(env,id){await env.DB.prepare(`INSERT INTO users(email,display_name,last_login_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(email) DO UPDATE SET display_name=excluded.display_name,last_login_at=CURRENT_TIMESTAMP`).bind(id.email,id.name).run();return env.DB.prepare('SELECT id,email,display_name FROM users WHERE lower(email)=?').bind(id.email).first();}
async function role(env,email){const r=await env.DB.prepare(`SELECT m.role FROM event_memberships m JOIN users u ON u.id=m.user_id JOIN events e ON e.id=m.event_id WHERE e.slug=? AND lower(u.email)=?`).bind(EVENT,email).first();return r?.role||'guest';}
async function ensureMember(request,env){const id=await accessIdentity(request,env,env.MEMBER_AUD);const u=await upsertUser(env,id);const eid=await eventId(env);await env.DB.prepare(`INSERT OR IGNORE INTO event_memberships(event_id,user_id,role) VALUES(?,?, 'guest')`).bind(eid,u.id).run();return {...id,user_id:u.id,role:await role(env,id.email)};}
async function ensureOrganizer(request,env){const id=await accessIdentity(request,env,env.ORGANIZER_AUD);const u=await upsertUser(env,id);const r=await role(env,id.email);if(r!=='organizer')throw new Error('Organizer role required');return {...id,user_id:u.id,role:r};}
async function body(req){try{return await req.json()}catch{return {}}}
const val=(o,k,d='')=>clean(o[k])??d;

// Runtime safety net: IaC migrations remain canonical, but this lets the first API request initialize an empty D1 automatically.
let bootstrapped=false;
async function ensureSchema(env){if(bootstrapped)return;try{await env.DB.prepare('SELECT 1 FROM schema_meta LIMIT 1').first();bootstrapped=true;return;}catch{}
 const statements=[
`CREATE TABLE IF NOT EXISTS schema_meta(version INTEGER NOT NULL,applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY AUTOINCREMENT,slug TEXT NOT NULL UNIQUE,title TEXT NOT NULL,subtitle TEXT,destination TEXT,start_date TEXT,end_date TEXT,welcome_message TEXT,host_lodging_status TEXT DEFAULT 'Not booked yet',host_hotel TEXT,status TEXT NOT NULL DEFAULT 'draft',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT NOT NULL UNIQUE COLLATE NOCASE,display_name TEXT,last_login_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS event_memberships(event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,role TEXT NOT NULL DEFAULT 'guest' CHECK(role IN('organizer','guest')),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(event_id,user_id))`,
`CREATE TABLE IF NOT EXISTS hotels(id INTEGER PRIMARY KEY AUTOINCREMENT,event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,name TEXT NOT NULL,room_type TEXT,area TEXT DEFAULT 'Oak Bluffs',nightly_rate REAL,booking_url TEXT,notes TEXT,sort_order INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1)`,
`CREATE TABLE IF NOT EXISTS budget_items(id INTEGER PRIMARY KEY AUTOINCREMENT,event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,label TEXT NOT NULL,detail TEXT,amount_text TEXT NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1)`,
`CREATE TABLE IF NOT EXISTS activities(id INTEGER PRIMARY KEY AUTOINCREMENT,event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,title TEXT NOT NULL,description TEXT,location TEXT,event_date TEXT,event_time TEXT,cost_text TEXT,status TEXT NOT NULL DEFAULT 'published',category TEXT,sort_order INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS activity_ideas(id INTEGER PRIMARY KEY AUTOINCREMENT,event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,title TEXT NOT NULL,category TEXT,description TEXT,suggested_date TEXT,suggested_time TEXT,meeting_place TEXT,status TEXT NOT NULL DEFAULT 'approved',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS activity_responses(activity_id INTEGER NOT NULL REFERENCES activity_ideas(id) ON DELETE CASCADE,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,response TEXT NOT NULL CHECK(response IN('going','interested')),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(activity_id,user_id))`,
`CREATE TABLE IF NOT EXISTS guest_book_entries(id INTEGER PRIMARY KEY AUTOINCREMENT,event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'published',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS announcements(id INTEGER PRIMARY KEY AUTOINCREMENT,event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,title TEXT NOT NULL,body TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'published',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS content_sections(id INTEGER PRIMARY KEY AUTOINCREMENT,event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,key TEXT NOT NULL,label TEXT NOT NULL,value TEXT,UNIQUE(event_id,key))`,
`CREATE TABLE IF NOT EXISTS photos(id INTEGER PRIMARY KEY AUTOINCREMENT,event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,user_id INTEGER REFERENCES users(id),object_key TEXT NOT NULL,caption TEXT,status TEXT NOT NULL DEFAULT 'published',content_type TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE INDEX IF NOT EXISTS idx_hotels_event ON hotels(event_id)`,`CREATE INDEX IF NOT EXISTS idx_costs_event ON budget_items(event_id)`,`CREATE INDEX IF NOT EXISTS idx_activities_event ON activities(event_id)`,`CREATE INDEX IF NOT EXISTS idx_ideas_event ON activity_ideas(event_id)`,`CREATE INDEX IF NOT EXISTS idx_announcements_event ON announcements(event_id)`];
 for(const sql of statements) await env.DB.prepare(sql).run();
 await env.DB.prepare(`INSERT OR IGNORE INTO events(slug,title,subtitle,destination,start_date,end_date,welcome_message,status) VALUES(?,?,?,?,?,?,?,'published')`).bind(EVENT,"Trina's 60th Birthday & Retirement Trip","Martha's Vineyard · Oak Bluffs, Massachusetts","Martha's Vineyard, Massachusetts",'2029-08-05','2029-08-18',"Join Trina for a special birthday and retirement trip to Martha's Vineyard.").run();
 const eid=await eventId(env);
 const seed=async(table,cols,rows)=>{const count=await env.DB.prepare(`SELECT COUNT(*) c FROM ${table} WHERE event_id=?`).bind(eid).first();if(count.c>0)return;for(const row of rows){const q=`INSERT INTO ${table}(event_id,${cols.join(',')}) VALUES(?,${cols.map(()=>'?').join(',')})`;await env.DB.prepare(q).bind(eid,...row).run();}};
 await seed('hotels',['name','room_type','area','nightly_rate','sort_order'],[["Narragansett House","1-bedroom","Oak Bluffs",575,1],["Pequot Hotel","3-bedroom","Oak Bluffs",1300,2],["The Oak Bluffs Inn","2-bedroom","Oak Bluffs",1250,3],["Island Inn","2-bedroom","Oak Bluffs",1000,4],["Dockside Inn","Deluxe Suite","Oak Bluffs",850,5],["Madison Inn","Extended Stay","Oak Bluffs",650,6]]);
 await seed('budget_items',['label','detail','amount_text','sort_order'],[["Flights","round trip","$900",1],["Ubers","airport to ferry","$460",2],["Ferry","both ways","$144",3],["African American Film Festival","9-day passes","$2,000",4],["Food","per day","$250 per day",5],["Other Activities","","TBD",6]]);
 await seed('activities',['title','description','location','event_time','cost_text','category','sort_order'],[["Inkwell Beach","","Inkwell Beach","","Free","Beach & Water",1],["South Beach","","South Beach","","Free","Beach & Water",2],["Beach Yoga with Christopher Simms","Beach yoga with Christopher Simms.","Inkwell Beach","","Free","Wellness",3],["The Polar Bears","Morning plunge, water aerobics and stretching.","Inkwell Beach","7:30 AM","Free","Wellness",4],["African American Film Festival","9-day passes for two people.","","","$2,000","Entertainment",5]]);
 const content=[["home_intro","Home introduction","A beautiful island getaway to celebrate Trina's 60th birthday and retirement—together."],["travel_intro","Travel introduction","Martha's Vineyard is an island off the coast of Massachusetts. Plan your airport-to-ferry connection before you travel."],["stay_intro","Stay introduction","Everyone will book their own lodging. Staying in or near Oak Bluffs keeps you close to the ferry, shops, restaurants, beaches, and the center of the trip."],["budget_intro","Costs introduction","Use these planning estimates to build your own trip budget. Food is priced per day and hotels are priced per night."],["plans_intro","Plans introduction","Confirmed trip plans will live at the top. Everything else is inspiration—ideas guests can suggest, join, and turn into meetups."],["explore_intro","Explore introduction","Use Trina's notes as inspiration for food, culture, shopping, beaches, wellness, and island adventures."],["before_intro","Before You Go introduction","A little preparation will make the island experience easier and more comfortable."],["community_intro","Community introduction","Guests can sign in to add ideas, join activities, leave messages, and share trip memories."],["about_intro","About Martha's Vineyard introduction","Get to know Martha's Vineyard, Oak Bluffs, and the history and culture that make this destination special."]];
 for(const r of content)await env.DB.prepare('INSERT OR IGNORE INTO content_sections(event_id,key,label,value) VALUES(?,?,?,?)').bind(eid,...r).run();
 for(const [email,name] of [[env.OWNER_EMAIL,'Angela'],[env.TRINA_EMAIL,'Trina James']]){await env.DB.prepare('INSERT OR IGNORE INTO users(email,display_name) VALUES(?,?)').bind(email,name).run();const u=await env.DB.prepare('SELECT id FROM users WHERE lower(email)=?').bind(email.toLowerCase()).first();await env.DB.prepare(`INSERT INTO event_memberships(event_id,user_id,role) VALUES(?,?,'organizer') ON CONFLICT(event_id,user_id) DO UPDATE SET role='organizer'`).bind(eid,u.id).run();}
 await env.DB.prepare('DELETE FROM schema_meta').run();await env.DB.prepare('INSERT INTO schema_meta(version) VALUES(1)').run();bootstrapped=true;
}

async function publicBootstrap(env){const eid=await eventId(env);const [event,hotels,costs,activities,ideas,guestbook,announcements,contentRows]=await Promise.all([
 env.DB.prepare('SELECT * FROM events WHERE id=?').bind(eid).first(),env.DB.prepare('SELECT * FROM hotels WHERE event_id=? AND active=1 ORDER BY sort_order,id').bind(eid).all(),env.DB.prepare('SELECT * FROM budget_items WHERE event_id=? AND active=1 ORDER BY sort_order,id').bind(eid).all(),env.DB.prepare(`SELECT * FROM activities WHERE event_id=? AND status='published' ORDER BY sort_order,id`).bind(eid).all(),env.DB.prepare(`SELECT a.*,u.display_name,u.email,SUM(CASE WHEN r.response='going' THEN 1 ELSE 0 END) going_count,SUM(CASE WHEN r.response='interested' THEN 1 ELSE 0 END) interested_count FROM activity_ideas a LEFT JOIN users u ON u.id=a.created_by LEFT JOIN activity_responses r ON r.activity_id=a.id WHERE a.event_id=? AND a.status='approved' GROUP BY a.id ORDER BY a.created_at DESC`).bind(eid).all(),env.DB.prepare(`SELECT g.*,u.display_name FROM guest_book_entries g LEFT JOIN users u ON u.id=g.user_id WHERE g.event_id=? AND g.status='published' ORDER BY g.created_at DESC LIMIT 50`).bind(eid).all(),env.DB.prepare(`SELECT * FROM announcements WHERE event_id=? AND status='published' ORDER BY created_at DESC`).bind(eid).all(),env.DB.prepare('SELECT key,value FROM content_sections WHERE event_id=?').bind(eid).all()]);
 return {event,hotels:hotels.results,costs:costs.results,activities:activities.results,ideas:ideas.results,guestbook:guestbook.results,announcements:announcements.results,content:Object.fromEntries(contentRows.results.map(x=>[x.key,x.value]))};}

async function memberBootstrap(env,me){const eid=await eventId(env);const ideas=await env.DB.prepare(`SELECT a.*,SUM(CASE WHEN r.response='going' THEN 1 ELSE 0 END) going_count,SUM(CASE WHEN r.response='interested' THEN 1 ELSE 0 END) interested_count,(SELECT response FROM activity_responses mine WHERE mine.activity_id=a.id AND mine.user_id=?) my_response FROM activity_ideas a LEFT JOIN activity_responses r ON r.activity_id=a.id WHERE a.event_id=? AND (a.status='approved' OR a.created_by=?) GROUP BY a.id ORDER BY a.created_at DESC`).bind(me.user_id,eid,me.user_id).all();const guestbook=await env.DB.prepare(`SELECT g.*,u.display_name FROM guest_book_entries g LEFT JOIN users u ON u.id=g.user_id WHERE g.event_id=? AND g.status='published' ORDER BY g.created_at DESC LIMIT 50`).bind(eid).all();const photos=await env.DB.prepare(`SELECT p.id,p.caption,p.created_at,u.display_name FROM photos p LEFT JOIN users u ON u.id=p.user_id WHERE p.event_id=? AND p.status='published' ORDER BY p.created_at DESC LIMIT 100`).bind(eid).all();return {me,ideas:ideas.results,guestbook:guestbook.results,photos:photos.results};}

export default {async fetch(request,env){const url=new URL(request.url),p=url.pathname;try{await ensureSchema(env);
 if(p==='/api/health')return j({ok:true,app:'vacaybuilder',database:'d1',event:EVENT});
 if(p==='/api/public/bootstrap')return j(await publicBootstrap(env));
 if(p.startsWith('/api/public/photo/')){const id=Number(p.split('/').pop());const row=await env.DB.prepare(`SELECT object_key,content_type FROM photos WHERE id=? AND status='published'`).bind(id).first();if(!row)return new Response('Not found',{status:404});if(!env.PHOTOS)return new Response('Photo storage not configured',{status:503});const obj=await env.PHOTOS.get(row.object_key);if(!obj)return new Response('Not found',{status:404});const h=new Headers();h.set('content-type',row.content_type||obj.httpMetadata?.contentType||'application/octet-stream');h.set('cache-control','public,max-age=3600');return new Response(obj.body,{headers:h});}

 if(p.startsWith('/member')){const me=await ensureMember(request,env);if(p==='/member.html'||p==='/member'||p==='/member/')return env.ASSETS.fetch(request);if(p==='/member/api/bootstrap')return j(await memberBootstrap(env,me));if(p==='/member/api/ideas'&&request.method==='POST'){const b=await body(request);if(!val(b,'title'))return j({error:'Idea title is required'},400);const eid=await eventId(env);await env.DB.prepare(`INSERT INTO activity_ideas(event_id,created_by,title,category,description,suggested_date,suggested_time,meeting_place,status) VALUES(?,?,?,?,?,?,?,?, 'approved')`).bind(eid,me.user_id,val(b,'title'),val(b,'category'),val(b,'description'),val(b,'suggested_date'),val(b,'suggested_time'),val(b,'meeting_place')).run();return j({ok:true},201);}if(/^\/member\/api\/ideas\/\d+\/response$/.test(p)&&request.method==='PUT'){const id=Number(p.split('/')[4]),b=await body(request);if(!['going','interested'].includes(b.response))return j({error:'Invalid response'},400);await env.DB.prepare(`INSERT INTO activity_responses(activity_id,user_id,response) VALUES(?,?,?) ON CONFLICT(activity_id,user_id) DO UPDATE SET response=excluded.response`).bind(id,me.user_id,b.response).run();return j({ok:true});}if(p==='/member/api/guestbook'&&request.method==='POST'){const b=await body(request);if(!val(b,'message'))return j({error:'Message is required'},400);const eid=await eventId(env);await env.DB.prepare(`INSERT INTO guest_book_entries(event_id,user_id,message,status) VALUES(?,?,?,'published')`).bind(eid,me.user_id,val(b,'message')).run();return j({ok:true},201);}if(p==='/member/api/photos'&&request.method==='POST'){if(!env.PHOTOS)return j({error:'Photo storage is not configured yet'},503);const fd=await request.formData(),file=fd.get('photo'),caption=String(fd.get('caption')||'').trim();if(!(file instanceof File)||!file.size)return j({error:'Choose a photo'},400);if(file.size>10*1024*1024)return j({error:'Photo must be 10 MB or smaller'},400);if(!['image/jpeg','image/png','image/webp'].includes(file.type))return j({error:'Use JPEG, PNG or WebP'},400);const eid=await eventId(env),ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg',key=`${EVENT}/${crypto.randomUUID()}.${ext}`;await env.PHOTOS.put(key,file.stream(),{httpMetadata:{contentType:file.type}});await env.DB.prepare(`INSERT INTO photos(event_id,user_id,object_key,caption,status,content_type) VALUES(?,?,?,?, 'published',?)`).bind(eid,me.user_id,key,caption,file.type).run();return j({ok:true},201);}return j({error:'Member endpoint not found'},404);}

 if(p.startsWith('/admin')){const me=await ensureOrganizer(request,env);if(p==='/admin.html'||p==='/admin'||p==='/admin/')return env.ASSETS.fetch(request);if(p==='/admin/api/me')return j(me);const eid=await eventId(env);
  if(p==='/admin/api/trip'){if(request.method==='GET')return j(await env.DB.prepare('SELECT * FROM events WHERE id=?').bind(eid).first());if(request.method==='PUT'){const b=await body(request);await env.DB.prepare(`UPDATE events SET title=?,subtitle=?,destination=?,start_date=?,end_date=?,welcome_message=?,host_lodging_status=?,host_hotel=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(val(b,'title'),val(b,'subtitle'),val(b,'destination'),val(b,'start_date'),val(b,'end_date'),val(b,'welcome_message'),val(b,'host_lodging_status'),val(b,'host_hotel'),eid).run();return j({ok:true});}}
  const defs={hotels:{table:'hotels',fields:['name','room_type','area','nightly_rate','booking_url','notes']},costs:{table:'budget_items',fields:['label','detail','amount_text']},activities:{table:'activities',fields:['title','category','location','event_date','event_time','cost_text','description']},announcements:{table:'announcements',fields:['title','body','status']}};
  for(const [route,d] of Object.entries(defs)){if(p===`/admin/api/${route}`){if(request.method==='GET'){const r=await env.DB.prepare(`SELECT * FROM ${d.table} WHERE event_id=? ORDER BY sort_order,id`).bind(eid).all();return j(r.results);}if(request.method==='POST'){const b=await body(request),cols=['event_id',...d.fields],vals=[eid,...d.fields.map(f=>val(b,f,null))];await env.DB.prepare(`INSERT INTO ${d.table}(${cols.join(',')}) VALUES(${cols.map(()=>'?').join(',')})`).bind(...vals).run();return j({ok:true},201);}}const m=p.match(new RegExp(`^/admin/api/${route}/(\\d+)$`));if(m){const id=Number(m[1]);if(request.method==='PUT'){const b=await body(request);await env.DB.prepare(`UPDATE ${d.table} SET ${d.fields.map(f=>`${f}=?`).join(',')} WHERE id=? AND event_id=?`).bind(...d.fields.map(f=>val(b,f,null)),id,eid).run();return j({ok:true});}if(request.method==='DELETE'){await env.DB.prepare(`DELETE FROM ${d.table} WHERE id=? AND event_id=?`).bind(id,eid).run();return j({ok:true});}}}
  if(p==='/admin/api/page-text'){const r=await env.DB.prepare('SELECT * FROM content_sections WHERE event_id=? ORDER BY id').bind(eid).all();return j(r.results);}let m=p.match(/^\/admin\/api\/page-text\/(\d+)$/);if(m&&request.method==='PUT'){const b=await body(request);await env.DB.prepare('UPDATE content_sections SET value=? WHERE id=? AND event_id=?').bind(val(b,'value'),Number(m[1]),eid).run();return j({ok:true});}
  if(p==='/admin/api/ideas'){const r=await env.DB.prepare(`SELECT a.*,u.email FROM activity_ideas a LEFT JOIN users u ON u.id=a.created_by WHERE a.event_id=? ORDER BY a.created_at DESC`).bind(eid).all();return j(r.results);}if(p==='/admin/api/guestbook'){const r=await env.DB.prepare(`SELECT g.*,u.email FROM guest_book_entries g LEFT JOIN users u ON u.id=g.user_id WHERE g.event_id=? ORDER BY g.created_at DESC`).bind(eid).all();return j(r.results);}if(p==='/admin/api/photos'){const r=await env.DB.prepare(`SELECT p.*,u.email FROM photos p LEFT JOIN users u ON u.id=p.user_id WHERE p.event_id=? ORDER BY p.created_at DESC`).bind(eid).all();return j(r.results);}m=p.match(/^\/admin\/api\/moderate\/(idea|guestbook|photo)\/(\d+)$/);if(m&&request.method==='PUT'){const b=await body(request),table=m[1]==='idea'?'activity_ideas':m[1]==='guestbook'?'guest_book_entries':'photos';await env.DB.prepare(`UPDATE ${table} SET status=? WHERE id=? AND event_id=?`).bind(val(b,'status'),Number(m[2]),eid).run();return j({ok:true});}
  if(p==='/admin/api/people'){if(request.method==='GET'){const r=await env.DB.prepare(`SELECT u.id,u.email,u.display_name,m.role FROM event_memberships m JOIN users u ON u.id=m.user_id WHERE m.event_id=? ORDER BY CASE m.role WHEN 'organizer' THEN 0 ELSE 1 END,u.email`).bind(eid).all();return j(r.results);}if(request.method==='POST'){const b=await body(request),email=String(b.email||'').trim().toLowerCase(),rr=b.role==='organizer'?'organizer':'guest';if(!email.includes('@'))return j({error:'Valid email required'},400);await env.DB.prepare('INSERT OR IGNORE INTO users(email,display_name) VALUES(?,?)').bind(email,email.split('@')[0]).run();const u=await env.DB.prepare('SELECT id FROM users WHERE lower(email)=?').bind(email).first();await env.DB.prepare(`INSERT INTO event_memberships(event_id,user_id,role) VALUES(?,?,?) ON CONFLICT(event_id,user_id) DO UPDATE SET role=excluded.role`).bind(eid,u.id,rr).run();return j({ok:true});}}
  return j({error:'Admin endpoint not found'},404);
 }
 return env.ASSETS.fetch(request);
 }catch(e){console.error(e);const msg=e?.message||'Request failed';if(p.startsWith('/admin')||p.startsWith('/member'))return j({error:msg},msg.includes('token')?401:msg.includes('Organizer')?403:500);return j({error:'Server error'},500);}}
};
